### PR TITLE
Full extract

### PR DESCRIPTION
**Pull request by pinbraerts**
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/geoplot/11)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 8 of 80 files at r1.
Review status: 8 of 76 files reviewed at latest revision, 11 unresolved discussions.

---

*[compile/Readme.md, line 1 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4s9B-kwQl-kFt_W08:-Kx4s9B-kwQl-kFt_W09:b6xwkx8) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/compile/Readme.md#L1)):*
> ```Markdown
> This is directory for C++ version of the Compiler
> ```

Когда будет этот твой компилятор на С++, тогда и каталог создашь. Только я боюсь, что его не будет.

Сейчас каталог и этот файл убери.

---

*[extract/compile.bat, line 3 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4sSwdGBXpVFxiePgK:-Kx4sSwdGBXpVFxiePgL:b-3gai0s) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/compile.bat#L3)):*
> ```Batchfile
> @echo off
> 
> python ..\python\compile\Compiler.py prims\%1 %~n1.proto ..\python\geometry\%~n1.py
> ```

"Компилятор" не нужен.

---

*[extract/extract, line 1 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4sfgEl3HLjivz4QLs:-Kx4sfgEl3HLjivz4QLt:bxt80mq) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract#L1)):*
> ```
> python extract.py $*
> ```

python3

---

*[extract/extract.bat, line 2 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4saBin533X7ew6ttw:-Kx4saBin533X7ew6ttx:bxt80mq) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.bat#L2)):*
> ```Batchfile
> @echo off
> python extract.py %*
> ```

python3

---

*[extract/extract.py, line 3 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4si5ukJlE5iIZ_g0N:-Kx4si5ukJlE5iIZ_g0O:b-99727k) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L3)):*
> ```Python
> import sys, os
> from glob import iglob
> from os.path import basename as bn, split as sp, dirname as dn, realpath as rp, join, splitext as spe
> ```

pep8 и ужасные нечитаемые сокращения

---

*[extract/extract.py, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4srmQO5e3CbX8Quao:-Kx4srmQO5e3CbX8Quap:boc3sd6) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L5)):*
> ```Python
> from os.path import basename as bn, split as sp, dirname as dn, realpath as rp, join, splitext as spe
> 
> lst = ["tomitaparser"]
> ```

что это это за лст?

---

*[extract/extract.py, line 17 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4t8hFVwzPHdZALaoj:-Kx4t8hFVwzPHdZALaok:berj73q) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L17)):*
> ```Python
>     lst += ["tomita-win32"]
>     def _findc(cmd):
>         return os.system("where /q " + cmd) == 0
> ```

а зачем искать tomita-win32, если можно просто запускать tomita-win32?

---

*[extract/extract.py, line 31 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4tQ9q7LFo1YuRcdKt:-Kx4tQ9q7LFo1YuRcdKu:b-7ce4of) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L31)):*
> ```Python
> mall = False
> norm = False
> mran = []
> ```

ничего не понятно

---

*[extract/normalize.py, line 11 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4tthTkBQ_0MwMCHNu:-Kx4tthTkBQ_0MwMCHNv:bb7mj2a) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/normalize.py#L11)):*
> ```Python
> 	tree._setroot(ET.Element("facts"))
> else:
> 	tree._setroot(doc.find("facts"))
> ```

pep8

---

*[extract/normalize.py, line 20 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4uBnuW1I0dWTcLS9d:-Kx4uBnuW1I0dWTcLS9e:bltgx46) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/normalize.py#L20)):*
> ```Python
> 
> tree.write(sys.argv[2], 'unicode', True)
> print("Normalized file", sys.argv[1])
> ```

это зачем?

---

*[extract/normalize.py, line 21 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4uEn25ugjWEVjVDSW:-Kx4uEn25ugjWEVjVDSX:bltgx46) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/normalize.py#L21)):*
> ```Python
> tree.write(sys.argv[2], 'unicode', True)
> print("Normalized file", sys.argv[1])
> print()
> ```

это зачем?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
Лист `lst` -- список команд, которые **могут быть** подходящими для данной платформы. По нему потом проходятся и находят первую работающую (`cmd = next(x for x in lst if findc(x))`).

**Comment by pinbraerts** [comment]
Полностью убрать сообщения о выполнении? Я думал, что нужно как-то сообщить, что файл обработан.

**Comment by pinbraerts** [comment]
У меня не `python3`, а `python`.

UPD: Внутри **extract.py** использую `sys.executable`.
UPD: В **bash** и **batch** добавил проверку на `python3`. Может, надо ещё `python3.x`? Как-то можно использовать **PYTHONHOME**? Гарантированно, что такая переменная есть? У меня её в командной строке нет. Может, если она не определена, то работает команда `python`?
UPD: Использовал `whereis python` для определения.

**Comment by pinbraerts** [comment]
Я использую `sys.executable`.

**Comment by pinbraerts** [comment]
*[extract/extract.bat, line 2 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4saBin533X7ew6ttw:-Kx7TgAaBSAK-jN6aA49:boety5w) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.bat#L2)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

python3
</blockquote></details>

У меня `python`, я переделал с помощью `whereis` для linux и проверки на python3 на Windows. Можно использовать **PYTHONHOME**? У меня он даже не определён в среде

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 3 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4si5ukJlE5iIZ_g0N:-Kx7uKnf0aOMO47b9eq6:bk30spg) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L3)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

pep8 и ужасные нечитаемые сокращения
</blockquote></details>

Исправил

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4srmQO5e3CbX8Quao:-Kx7uxXXmRU8Tg5HSkkH:b69n1iq) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L5)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

что это это за лст?
</blockquote></details>

Лист возможных имён томиты. Исправил на нормальное имя. Потом программа ищет первое подходящее имя.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 17 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4t8hFVwzPHdZALaoj:-Kx7vGZYvd09VMe6CIhL:b-9s5jri) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L17)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

а зачем искать tomita-win32, если можно просто запускать tomita-win32?
</blockquote></details>

Ищется не только `tomita-win32`, но и `tomitaparser`, который фигурирует в документации, и у меня такое имя парсера.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 31 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4tQ9q7LFo1YuRcdKt:-Kx7v_UQccqrdn4j47-z:b-1t715q) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.py#L31)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

ничего не понятно
</blockquote></details>

Исправил на понятные номера: это были опции.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
*[extract/normalize.py, line 11 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4tthTkBQ_0MwMCHNu:-Kx7vhMQyqL2xcBzNVs1:bk30spg) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/normalize.py#L11)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

pep8
</blockquote></details>

Исправил

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by pinbraerts** [comment]
*[extract/normalize.py, line 20 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4uBnuW1I0dWTcLS9d:-Kx7vlnQmMU3_iW2n1Q-:b-3go21d) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/normalize.py#L20)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

это зачем?
</blockquote></details>

Убрал, но не понимаю, почему бы не сообщать, какой файл сейчас в обработке.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Comment by cblp** [comment]
Review status: 3 of 74 files reviewed at latest revision, 11 unresolved discussions.

---

*[extract/extract.bat, line 2 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/11#-Kx4saBin533X7ew6ttw:-Kx8GfkYPFMhi0dYRUS5:bpgu5l2) ([raw file](https://github.com/mcl1303/geoplot/blob/1908d6d609b8bed153014af7f036712e1818e19e/extract/extract.bat#L2)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

У меня `python`, я переделал с помощью `whereis` для linux и проверки на python3 на Windows. Можно использовать **PYTHONHOME**? У меня он даже не определён в среде
</blockquote></details>

PYTHONHOME не имеет отношения к вопросу, он не должен быть определён в нормальных условиях

`whereis` у меня на линуксе выдаёт совсем не то, что можно использовать в скриптах, в отличие от `which`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/11)*

**Pull request closed without merging**
