### PR TITLE
Решение Issue #30

### PR DESCRIPTION
**Pull request by pinbraerts**
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/geoplot/34)

### CODE REVIEW

**Comment by cblp** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 57 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/34#-KxqwiY0LN5NOAwkwL6f:-KxqwiY1nUSdcJhzVpn3:by5z78m) ([raw file](https://github.com/mcl1303/geoplot/blob/fd17609eb11ad7638c7cc7ec3b21178559b47ba0/extract/extract.py#L57)):*
> ```Python
>     for file in range_of_files:
>         print("Processing", file, "file", file=sys.stderr)
>         bnf = os.path.splitext(os.path.basename(file))[0]
> ```

Плохое название переменной

---

*[extract/extract.py, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/34#-KxqwviqtJCQNhW2q4Fj:-KxqwviqtJCQNhW2q4Fk:ben7nk5) ([raw file](https://github.com/mcl1303/geoplot/blob/fd17609eb11ad7638c7cc7ec3b21178559b47ba0/extract/extract.py#L58)):*
> ```Python
>         print("Processing", file, "file", file=sys.stderr)
>         bnf = os.path.splitext(os.path.basename(file))[0]
>         with open(input_path % bnf) as input_file:
> ```

Метод `format` считается более правильным, чем устаревший `%`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/34)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/34)*

**Comment by pinbraerts** [comment]
#30  #33 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/34#-:-KxrCMX4e4p9gUB4Dhxz:b-72ev3c)*

**Comment by pinbraerts** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 57 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/34#-KxqwiY0LN5NOAwkwL6f:-KxrCRWvliyy_vRD5PWb:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/fd17609eb11ad7638c7cc7ec3b21178559b47ba0/extract/extract.py#L57)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Плохое название переменной
</blockquote></details>

Done.

---

*[extract/extract.py, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/34#-KxqwviqtJCQNhW2q4Fj:-KxrCc9RGd0-z0nqVPsl:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/fd17609eb11ad7638c7cc7ec3b21178559b47ba0/extract/extract.py#L58)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Метод `format` считается более правильным, чем устаревший `%`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/34)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/34)*

**Pull request merged**
