### PR TITLE
Build model

### PR DESCRIPTION
**Pull request by pinbraerts**
В `Segment.py` выдавало ошибку "frozenset does not support indexing",
исправил. Заодно сделал #27

---
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/geoplot/35)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 2 of 7 files at r1, 3 of 11 files at r3.
Review status: 5 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[model/geometry/__init__.py, line 28 at r3](https://reviewable.io:443/reviews/mcl1303/geoplot/35#-KzJD6yf1t6bz0BSf3CA:-KzJD6yf1t6bz0BSf3CB:b-i82pa0) ([raw file](https://github.com/mcl1303/geoplot/blob/f391451c4b2f9a971528263fa6c83d415f121240/model/geometry/__init__.py#L28)):*
> ```Python
>     if isinstance(obj, frozenset):
>         return list(obj)
>     elif isclass(obj):
> ```

isinstance(obj, type)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/35)*

**Comment by cblp** [comment]
Reviewed 8 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/35)*

**Comment by pinbraerts** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[model/geometry/__init__.py, line 28 at r3](https://reviewable.io:443/reviews/mcl1303/geoplot/35#-KzJD6yf1t6bz0BSf3CA:-KzJwITiadRNMIJ4Ui6r:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/f391451c4b2f9a971528263fa6c83d415f121240/model/geometry/__init__.py#L28)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

isinstance(obj, type)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/35)*

**Review by axvoff — APPROVED** [review]

**Review by axvoff — APPROVED** [review]

**Review by axvoff — APPROVED** [review]

**Review by axvoff — APPROVED** [review]

**Comment by axvoff** [comment]
Reviewed 2 of 7 files at r1, 10 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/35)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/35)*

**Pull request merged**
