### PR TITLE
Добавил install и сделал chmod

### PR DESCRIPTION
**Pull request by pinbraerts**
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/geoplot/24)

### CODE REVIEW

**Comment by cblp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/install.sh, line 1 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBNRLd2hS5qMkN3PN:-KxdBNRLd2hS5qMkN3PO:b-lrxkwr) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L1)):*
> ```Shell
> #!/usr/bin/env sh
> ```

#!/bin/bash
set -eux -o pipefail

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 2 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBX9Q_Hd6REjggh2a:-KxdBX9Q_Hd6REjggh2b:bpeufh6) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/.travis.yml#L2)):*
> ```YAML
> script: test/compare.py
> install: test/install.sh
> ```

Трэвису плевать, в каком порядке эти вещи написаны, но для людей лучше написать сначала install, потом script

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/install.sh, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBheIOLSwBO-YscAs:-KxdBheIOLSwBO-YscAt:b-4ohwnl) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L5)):*
> ```Shell
> wget http://download.cdn.yandex.net/tomita/tomita-linux64.bz2 -O /tmp/tomita.bz2
> bunzip2 /tmp/tomita.bz2 /usr/bin/
> chmod +x /usr/bin/tomita-linux64
> ```

а он там разве не исполнимый?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 1 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBNRLd2hS5qMkN3PN:-KxdBz_XM4b5ky6PtVUG:b-8kn8tc) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L1)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

#!/bin/bash
set -eux -o pipefail
</blockquote></details>

Зачем вторая строчка?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBheIOLSwBO-YscAs:-KxdC3LaYkqzB0XdVN-Z:bdlr1uh) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L5)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

а он там разве не исполнимый?
</blockquote></details>

Мне надо было делать chmod на Убунту, вроде

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/install.sh, line 4 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBwF7selnpOJ5IoQM:-KxdBwF7selnpOJ5IoQN:bt7i5m1) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L4)):*
> ```Shell
> 
> wget http://download.cdn.yandex.net/tomita/tomita-linux64.bz2 -O /tmp/tomita.bz2
> bunzip2 /tmp/tomita.bz2 /usr/bin/
> ```

Что ты ожидаешь, передавая /usr/bin/?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 4 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBwF7selnpOJ5IoQM:-KxdCDIFLb_eeL7VUmUP:bsoj7cq) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L4)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Что ты ожидаешь, передавая /usr/bin/?
</blockquote></details>

Последний разве не выходной файл?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[test/install.sh, line 1 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBNRLd2hS5qMkN3PN:-KxdCIbonYrGYtZnP7eI:bf7vg8t) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L1)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Зачем вторая строчка?
</blockquote></details>

Для логгирования команд и отлова типичных ошибок. Я просто привык писать это в каждом скрипте и тебе советую завести такую привычку.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 4 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBwF7selnpOJ5IoQM:-KxdCU9LV7LqjTccnHpV:b-51cys3) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L4)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Последний разве не выходной файл?
</blockquote></details>

По ошибке понятно, что нет

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[test/install.sh, line 4 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBwF7selnpOJ5IoQM:-KxdC_BOOinZZ4abyCLX:buhbk1t) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L4)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

По ошибке понятно, что нет
</blockquote></details>

man bunzip2

---

*[test/install.sh, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBheIOLSwBO-YscAs:-KxdCdIKJ0V1pbp97bLm:b-x0rqa2) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L5)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Мне надо было делать chmod на Убунту, вроде
</blockquote></details>

ну ладно, не помешает

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 4 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBwF7selnpOJ5IoQM:-KxdCqW3xghaMBXcYo8r:bywy3k7) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L4)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

man bunzip2
</blockquote></details>

У меня страницы man для него нет

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[test/install.sh, line 4 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBwF7selnpOJ5IoQM:-KxdDL6cTWdRHUPlbwJl:byskla6) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/test/install.sh#L4)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

У меня страницы man для него нет
</blockquote></details>

http://lmgtfy.com/?q=man+bunzip2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[.travis.yml, line 2 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdBX9Q_Hd6REjggh2a:-KxdCacOIkuihQWsQj3k:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/18553d8fef3818881a8e387f07f716f9d0504997/.travis.yml#L2)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Трэвису плевать, в каком порядке эти вещи написаны, но для людей лучше написать сначала install, потом script
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
Если томита будет в extract, её распознает `which`?

**Comment by cblp** [comment]
> Если томита будет в extract, её распознает which?

which смотрит в PATH, соответственно, если extract добавить в PATH, то найдёт

---

Reviewed 3 of 3 files at r5.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[extract/Point.cxx, line 0 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNnV313CsC1F0clKh:-KxdNnV4Z9IgG8pdavI0:b3kre) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/extract/Point.cxx#L0)):*
?

---

*[test/install.sh, line 3 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNrezHBjoIcz6eAvW:-KxdNrezHBjoIcz6eAvX:b7nrk5f) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L3)):*
> ```Shell
> #!/bin/bash
> set -eux -o pipefail
> pwd
> ```

Для отладки?

---

*[test/install.sh, line 7 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNu3CS9VaA1zO8vmi:-KxdNu3CS9VaA1zO8vmj:b4zzm1b) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L7)):*
> ```Shell
> bunzip2 tomita-linux64.bz2
> chmod +x tomita-linux64
> PATH=$PATH;`pwd`
> ```

нужны кавычки

---

*[test/install.sh, line 7 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNw_gLIJtaVJ6QycM:-KxdNw_gLIJtaVJ6QycN:b-ttstaj) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L7)):*
> ```Shell
> bunzip2 tomita-linux64.bz2
> chmod +x tomita-linux64
> PATH=$PATH;`pwd`
> ```

эта переменная умрёт вместе со скриптом. чтобы она осталась, надо

(1) либо написать её прямо в `.travis.yml`,

(2) либо вызывать этот скрипт из `.travis.yml` через команду `source`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-:-KxdNWFf9E2GSDYi0ks-:b-lecskn)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[extract/Point.cxx, line  at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNnV313CsC1F0clKh:-KxdPDFK83qi0OsqolWb:b9fvgs) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/extract/Point.cxx#L)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

?
</blockquote></details>

Я сам не знаю, почему это постоянно тут, его не должно быть

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 3 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNrezHBjoIcz6eAvW:-KxdPKRHBptRwQLflt3y:b-e2o0fp) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L3)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Для отладки?
</blockquote></details>

Вы сами написали поставить

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/install.sh, line 3 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNrezHBjoIcz6eAvW:-KxdQFzCbiLMo-RbgZWh:bbpa5hs) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L3)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Вы сами написали поставить
</blockquote></details>

где?

---

*[test/install.sh, line 7 at r6](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdQKLBDrFRnDChLT23:-KxdQKLBDrFRnDChLT24:b3kr9) ([raw file](https://github.com/mcl1303/geoplot/blob/cf1b2ff29d456256f41b07b1262379c2ab4f9747/test/install.sh#L7)):*
> ```Shell
> bunzip2 tomita-linux64.bz2
> chmod +x tomita-linux64
> PATH="$PATH;`pwd`"
> ```

:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[extract/Point.cxx, line  at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNnV313CsC1F0clKh:-KxdQRovLaEaqNruX6HV:b-5x9x91) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/extract/Point.cxx#L)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Я сам не знаю, почему это постоянно тут, его не должно быть
</blockquote></details>

нет, не постоянно. я первый раз вижу. вижу, что ты удалил файл. верни его обратно.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[extract/Point.cxx, line  at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNnV313CsC1F0clKh:-KxdQkXXStcYVGdYW9xF:b-nre0s5) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/extract/Point.cxx#L)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

нет, не постоянно. я первый раз вижу. вижу, что ты удалил файл. верни его обратно.
</blockquote></details>

Он тут не нужен

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[test/install.sh, line 3 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNrezHBjoIcz6eAvW:-KxdQoQZbUbseYU7FAFI:bpae40z) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L3)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

где?
</blockquote></details>

`pwd` я убрал, просто комментарий под `set -eux -o pipefail`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[extract/Point.cxx, line  at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNnV313CsC1F0clKh:-KxdRID0hmDiohk7c3KZ:b-3hlg7o) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/extract/Point.cxx#L)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Он тут не нужен
</blockquote></details>

Он не нужен в проекте?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 1 at r7](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdRbA0qogVOozDktTX:-KxdRbA0qogVOozDktTY:baqzaoj) ([raw file](https://github.com/mcl1303/geoplot/blob/8b4949c19212a0f1556dd5191aeac562bc8e8d61/.travis.yml#L1)):*
> ```YAML
> install: test/install.sh
> ```

```yaml
install:
  - test/install
  - export PATH="$PATH:`pwd`"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[extract/Point.cxx, line  at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNnV313CsC1F0clKh:-KxdS3Bt5dpY9DWjVpFv:b-ndzgq) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/extract/Point.cxx#L)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Он не нужен в проекте?
</blockquote></details>

Да, он лишний. Правильный файл лежит в `extract/grammars`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
*[.travis.yml, line 1 at r7](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdRbA0qogVOozDktTX:-KxdSDt0UL5elzuS1hYU:bvnpovq) ([raw file](https://github.com/mcl1303/geoplot/blob/8b4949c19212a0f1556dd5191aeac562bc8e8d61/.travis.yml#L1)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

```yaml
install:
  - test/install
  - export PATH="$PATH:`pwd`"
```
</blockquote></details>

В `.yml`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by pinbraerts** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 1 at r7](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdRbA0qogVOozDktTX:-KxdUFyAOpwvCWbjcV3M:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/8b4949c19212a0f1556dd5191aeac562bc8e8d61/.travis.yml#L1)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

В `.yml`?
</blockquote></details>

Done.

---

*[test/install.sh, line 7 at r5](https://reviewable.io:443/reviews/mcl1303/geoplot/24#-KxdNw_gLIJtaVJ6QycM:-KxdUGePONRtjhaNItVe:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/1f8d8d45fd857c84e5f345fa03fb866ce01fefbe/test/install.sh#L7)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

эта переменная умрёт вместе со скриптом. чтобы она осталась, надо

(1) либо написать её прямо в `.travis.yml`,

(2) либо вызывать этот скрипт из `.travis.yml` через команду `source`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Comment by cblp** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/24)*

**Pull request merged**
