### PR TITLE
Поправил extract

### PR DESCRIPTION
**Pull request by pinbraerts**
Теперь можно его запускать из любой директории

---
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/geoplot/20)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-KxbFPdmW_nXjb6KEBr-:bbwuppp) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
> ```Python
>         sys.stderr.write("Processed " + f + " file\n\n")
> 
>     os.chdir(working_dir)
> ```

Что будет, если не перейти обратно?

---

*[extract/Readme.md, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFm4zw0MByBhywfrm:-KxbFm4zw0MByBhywfrn:b-rqtcan) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/Readme.md#L5)):*
> ```Markdown
> 
> `tomitaparser` (or `tomita-$platformName`) **has to be** in PATH (`/usr/bin`)
> * in PATH (`/usr/bin`)
> ```

два раза подряд одно и то же написано?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-KxbUrfH1Jc6pBcuIqtc:buy2l9q) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Что будет, если не перейти обратно?
</blockquote></details>

Ну просто пользователь запускает программу в одной директории, а потом оказывается в другой. Я считаю, что это не хорошо

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by pinbraerts** [comment]
*[extract/Readme.md, line 5 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFm4zw0MByBhywfrm:-KxbWgTk6Wh80XT-TnUo:bk30spg) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/Readme.md#L5)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

два раза подряд одно и то же написано?
</blockquote></details>

Исправил

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-KxbZGHfI3kPhCyXpiNQ:b-a7v0pe) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

Ну просто пользователь запускает программу в одной директории, а потом оказывается в другой. Я считаю, что это не хорошо
</blockquote></details>

Нет, это же только процесс extract.py переходит. На оболочке пользователя это не должно отражаться.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 63 at r2](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbZhmyiz8XV4rumpln:-KxbZhmyiz8XV4rumplo:b-od9nne) ([raw file](https://github.com/mcl1303/geoplot/blob/d9b4bf216783da7f06f6725727bb45493025b6cd/extract/extract.py#L63)):*
> ```Python
>         bnf = os.path.splitext(os.path.basename(f))[0]
>         os.system(ext_cmd.format(bnf))
>         sys.stderr.write("Processed " + f + " file\n\n")
> ```

print(file=stderr)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 63 at r2](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbZhmyiz8XV4rumpln:-KxbZuRZt_1rLO9JXDyw:b-uu49bu) ([raw file](https://github.com/mcl1303/geoplot/blob/d9b4bf216783da7f06f6725727bb45493025b6cd/extract/extract.py#L63)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

print(file=stderr)
</blockquote></details>

а также print(end='\n\n')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-Kxb_4oGqO8ufvOM7-GF:b7alpvv) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Нет, это же только процесс extract.py переходит. На оболочке пользователя это не должно отражаться.
</blockquote></details>

```
\Desktop\GeoPlot>echo cd .. > tem.bat

\Desktop\GeoPlot>tem

\Desktop\GeoPlot>cd ..

\Desktop>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by pinbraerts** [comment]
*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-Kxb_vUDWvQ7C1Yy6nxP:b9l5t7m) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

```
\Desktop\GeoPlot>echo cd .. > tem.bat

\Desktop\GeoPlot>tem

\Desktop\GeoPlot>cd ..

\Desktop>
```
</blockquote></details>

```
\Desktop\GeoPlot>echo @echo off ^&^& cd .. > tem.bat

\Desktop\GeoPlot>tem

\Desktop>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-KxbaxLZpUQTNqFcZBAK:bkmu23t) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
<details><summary><i>Previously, pinbraerts (Dmitry) wrote…</i></summary><blockquote>

```
\Desktop\GeoPlot>echo @echo off ^&^& cd .. > tem.bat

\Desktop\GeoPlot>tem

\Desktop>
```
</blockquote></details>

Это у тебя интерпретатор bat кривой, он не создаёт новый процесс, а портит текущую оболочку. Ты на Питоне попробуй то же самое.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by pinbraerts** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[extract/extract.py, line 65 at r1](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbFPdmW_nXjb6KEBqz:-Kxbcw_vVor5Xj5pJadP:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/166ddcaaf6e992a50096e85ca6763b533e4be83c/extract/extract.py#L65)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Это у тебя интерпретатор bat кривой, он не создаёт новый процесс, а портит текущую оболочку. Ты на Питоне попробуй то же самое.
</blockquote></details>

Done.

---

*[extract/extract.py, line 63 at r2](https://reviewable.io:443/reviews/mcl1303/geoplot/20#-KxbZhmyiz8XV4rumpln:-Kxbc_RKorXTIPQbElnj:b-896fix) ([raw file](https://github.com/mcl1303/geoplot/blob/d9b4bf216783da7f06f6725727bb45493025b6cd/extract/extract.py#L63)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

а также print(end='\n\n')
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/geoplot/20)*

**Pull request merged**
